on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '16.16.0'
  AZURE_WEBAPP_NAME: ukhsa-temperature-alerts
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: ${{ secrets.DBUSER }}
          POSTGRES_USER: ${{ secrets.DBUSER }}
          POSTGRES_DB: ${{ secrets.DBNAME }}
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DBPASS: ${{ secrets.DBPASS }}
      DBUSER: ${{ secrets.DBUSER }}
      DBNAME: ${{ secrets.DBNAME }}

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'Create env file'
      run: |
        touch .env
        echo DBHOST=${{ secrets.DBHOST }} >> .env
        echo DBNAME=${{ secrets.DBNAME }} >> .env
        echo DBUSER=${{ secrets.DBUSER }} >> .env
        echo DBPASS=${{ secrets.DBPASS }} >> .env
    - name: Test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
